name: Blo main workflow

on:
  push:
    branch: 'develop'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update apt
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        run: sudo apt-get update

      - name: Install Mysql
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        run: sudo apt-get install mysql-server

      - name: Mysql start
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        run: mysql -u root

      - name: Create Database
        run: CREATE DATABASE blo;
        if: ${{ !contains(github.event.head_commit.message, '!!') }}

      - name: Use Database 'blo'
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        run: USE blo;

      - name: Exit in Mysql
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        run: exit

      - name: JDK Set up to 17
        uses: actions/setup-java@v3
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Gradlew
        run: chmod +x gradlew
        if: ${{ !contains(github.event.head_commit.message, '!!') }}

      - name: Build gradle
        run: ./gradlew --warning-mode=all build
        if: ${{ !contains(github.event.head_commit.message, '!!') }}
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          JWT_HEADER: ${{ secrets.JWT_HEADER }}
          JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
          JWT_ACCESS_TOKEN_EXP: ${{ secrets.JWT_ACCESS_TOKEN_EXP }}
          JWT_REFRESH_TOKEN_EXP: ${{ secrets.JWT_REFRESH_TOKEN_EXP }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Git remote update
        run: git remote update

      - name: Git change branch to 'develop'
        run: git checkout develop

      - name: Git pull in 'develop' branch
        run: git pull origin develop

      - name: Git change branch to 'main'
        run: git checkout main

      - name: Git pull in 'main' branch
        run: git pull origin main

      - name: Git set email
        run: git config --global user.email $EMAIL
        env:
          EMAIL: ${{ secrets.EMAIL }}

      - name: Git set name
        run: git config --global user.name $NAME
        env:
          NAME: ${{ secrets.NAME }}

      - name: Git merge 'develop' to 'main' branch
        run: git merge -X theirs --allow-unrelated-histories -m "Auto merge by Github Action" develop

      - name: Git push 'main' branch
        run: git push